23-Nov-2023 15:20:21.702 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
23-Nov-2023 15:20:21.702 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
23-Nov-2023 15:20:21.704 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@44b5848e')
23-Nov-2023 15:55:57.015 SEVERE [http-nio-8080-exec-15] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/readData.jsp] at line [20]

17:     <body>
18:         <%
19:             Conexao conexao = new Conexao();
20:             Connection con = conexao.abreConec();
21:             PreparedStatement st;
22: 
23:             try {


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.readData_jsp._jspService(readData_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 15:58:36.868 SEVERE [http-nio-8080-exec-20] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/readData.jsp] at line [20]

17:     <body>
18:         <%
19:             Conexao conexao = new Conexao();
20:             Connection con = conexao.abreConec();
21:             PreparedStatement st;
22: 
23:             try {


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.readData_jsp._jspService(readData_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 16:16:09.799 SEVERE [http-nio-8080-exec-23] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/readData.jsp] at line [20]

17:     <body>
18:         <%
19:             Conexao conexao = new Conexao();
20:             Connection con = conexao.abreConec();
21:             PreparedStatement st;
22: 
23:             try {


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.readData_jsp._jspService(readData_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 16:25:52.555 SEVERE [http-nio-8080-exec-16] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/readData.jsp] at line [21]

18:     <body>
19:         <%
20:             Conexao conexao = new Conexao();
21:             Connection con = conexao.abreConec();
22:             PreparedStatement st;
23: 
24:             try {


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.readData_jsp._jspService(readData_jsp.java:134)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 16:27:15.571 SEVERE [http-nio-8080-exec-21] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/readData.jsp] at line [21]

18:     <body>
19:         <%
20:             Conexao conexao = new Conexao();
21:             Connection con = conexao.abreConec();
22:             PreparedStatement st;
23: 
24:             try {


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.readData_jsp._jspService(readData_jsp.java:134)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 16:28:31.812 SEVERE [http-nio-8080-exec-19] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/readData.jsp] at line [21]

18:     <body>
19:         <%
20:             Conexao conexao = new Conexao();
21:             Connection con = conexao.abreConec();
22:             PreparedStatement st;
23: 
24:             try {


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.readData_jsp._jspService(readData_jsp.java:134)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 16:53:28.943 SEVERE [http-nio-8080-exec-15] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [22]

19:     <body>
20:         <%
21:         Conexao conexao = new Conexao();
22:             Connection con = conexao.abreConec();
23:             PreparedStatement st;
24:             String arquivo = "C:\\Users\\Desktop\\dados.csv";
25:             FileReader fr = new FileReader(arquivo);


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:139)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 16:54:13.625 SEVERE [http-nio-8080-exec-15] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception
	java.io.IOException: An exception occurred processing [/excel.jsp] at line [25]

22:             Connection con = conexao.abreConec();
23:             PreparedStatement st;*/
24:             String arquivo = "C:\\Users\\Desktop\\dados.csv";
25:             FileReader fr = new FileReader(arquivo);
26:             BufferedReader br = new BufferedReader(fr);
27:             String linha;
28:             while( (linha = br.readLine()) != null){


Stacktrace:
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:493)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: java.io.FileNotFoundException: C:\Users\Desktop\dados.csv (O sistema não pode encontrar o caminho especificado)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
		at java.base/java.io.FileReader.<init>(FileReader.java:60)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:142)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		... 25 more
23-Nov-2023 16:54:18.413 SEVERE [http-nio-8080-exec-18] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception
	java.io.IOException: An exception occurred processing [/excel.jsp] at line [25]

22:             Connection con = conexao.abreConec();
23:             PreparedStatement st;*/
24:             String arquivo = "C:\\Users\\Desktop\\dados.csv";
25:             FileReader fr = new FileReader(arquivo);
26:             BufferedReader br = new BufferedReader(fr);
27:             String linha;
28:             while( (linha = br.readLine()) != null){


Stacktrace:
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:493)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: java.io.FileNotFoundException: C:\Users\Desktop\dados.csv (O sistema não pode encontrar o caminho especificado)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
		at java.base/java.io.FileReader.<init>(FileReader.java:60)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:142)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		... 25 more
23-Nov-2023 16:54:28.892 SEVERE [http-nio-8080-exec-22] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception
	java.io.IOException: An exception occurred processing [/excel.jsp] at line [25]

22:             Connection con = conexao.abreConec();
23:             PreparedStatement st;*/
24:             String arquivo = "C:\\Users\\Desktop\\dados.csv";
25:             FileReader fr = new FileReader(arquivo);
26:             BufferedReader br = new BufferedReader(fr);
27:             String linha;
28:             while( (linha = br.readLine()) != null){


Stacktrace:
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:493)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: java.io.FileNotFoundException: C:\Users\Desktop\dados.csv (O sistema não pode encontrar o caminho especificado)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
		at java.base/java.io.FileReader.<init>(FileReader.java:60)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:142)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		... 25 more
23-Nov-2023 16:55:01.126 SEVERE [http-nio-8080-exec-22] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception
	java.io.IOException: java.io.FileNotFoundException: C:\Users\Desktop\dados.csv (O sistema não pode encontrar o caminho especificado)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:493)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: java.io.FileNotFoundException: C:\Users\Desktop\dados.csv (O sistema não pode encontrar o caminho especificado)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
		at java.base/java.io.FileReader.<init>(FileReader.java:60)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:142)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		... 25 more
23-Nov-2023 17:04:21.814 SEVERE [http-nio-8080-exec-32] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [32]

29:                 String[] dados = linha.split(";");
30: 
31:      
32:                 out.print("Hora: "+dados[0]+" Frequencia: "+dados[1]+"\n");
33:         
34:             }
35:             /*try {


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:149)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:04:22.996 SEVERE [http-nio-8080-exec-27] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [32]

29:                 String[] dados = linha.split(";");
30: 
31:      
32:                 out.print("Hora: "+dados[0]+" Frequencia: "+dados[1]+"\n");
33:         
34:             }
35:             /*try {


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:149)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:04:25.235 SEVERE [http-nio-8080-exec-34] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [32]

29:                 String[] dados = linha.split(";");
30: 
31:      
32:                 out.print("Hora: "+dados[0]+" Frequencia: "+dados[1]+"\n");
33:         
34:             }
35:             /*try {


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:149)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:04:26.415 SEVERE [http-nio-8080-exec-32] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [32]

29:                 String[] dados = linha.split(";");
30: 
31:      
32:                 out.print("Hora: "+dados[0]+" Frequencia: "+dados[1]+"\n");
33:         
34:             }
35:             /*try {


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:149)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:05:06.268 SEVERE [http-nio-8080-exec-26] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [32]

29:                 String[] dados = linha.split(";");
30: 
31:      
32:                 out.println("Hora: "+dados[0]+" Frequencia: "+dados[1]);
33:         
34:             }
35:             /*try {


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:149)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:05:34.437 SEVERE [http-nio-8080-exec-25] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [32]

29:                 String[] dados = linha.split(";");
30: 
31:      
32:                 out.println(dados[0]+" "+dados[1]);
33:         
34:             }
35:             /*try {


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:149)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:06:48.417 SEVERE [http-nio-8080-exec-33] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [33]

30: 
31:      
32:                 %>
33:                 <p><%= dados[0]%> - <%= dados[1]%></p>
34:                 <%
35:         
36:             }


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:152)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:06:49.555 SEVERE [http-nio-8080-exec-25] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [33]

30: 
31:      
32:                 %>
33:                 <p><%= dados[0]%> - <%= dados[1]%></p>
34:                 <%
35:         
36:             }


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:152)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:06:50.291 SEVERE [http-nio-8080-exec-34] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [33]

30: 
31:      
32:                 %>
33:                 <p><%= dados[0]%> - <%= dados[1]%></p>
34:                 <%
35:         
36:             }


Stacktrace:] with root cause
	java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:152)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:14:02.874 SEVERE [http-nio-8080-exec-29] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [Unable to compile class for JSP: 

An error occurred at line: [49] in the jsp file: [/excel.jsp]
Syntax error on tokens, delete these tokens
46:                 }
47:             }
48: 
49: */
50:         %>
51:     </body>
52: </html>


Stacktrace:] with root cause
	org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [49] in the jsp file: [/excel.jsp]
Syntax error on tokens, delete these tokens
46:                 }
47:             }
48: 
49: */
50:         %>
51:     </body>
52: </html>


Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:213)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:600)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:381)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:398)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:14:21.667 SEVERE [http-nio-8080-exec-27] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [24]

21:     <body>
22:         <%
23:             Conexao conexao = new Conexao();
24:             Connection con = conexao.abreConec();
25:             PreparedStatement st;
26:             
27:             String arquivo = "C:\\Users\\win\\Desktop\\dados.csv";


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:143)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:14:23.040 SEVERE [http-nio-8080-exec-33] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [24]

21:     <body>
22:         <%
23:             Conexao conexao = new Conexao();
24:             Connection con = conexao.abreConec();
25:             PreparedStatement st;
26:             
27:             String arquivo = "C:\\Users\\win\\Desktop\\dados.csv";


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:143)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:14:46.169 SEVERE [http-nio-8080-exec-32] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [Unable to compile class for JSP: 

An error occurred at line: [47] in the jsp file: [/excel.jsp]
Syntax error, insert "Finally" to complete TryStatement
44:                         }
45:                     }
46:                 }
47:             }
48: 
49: 
50:         %>


An error occurred at line: [177] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [180] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [180] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
response cannot be resolved

An error occurred at line: [183] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [185] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [188] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [191] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [192] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:] with root cause
	org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [47] in the jsp file: [/excel.jsp]
Syntax error, insert "Finally" to complete TryStatement
44:                         }
45:                     }
46:                 }
47:             }
48: 
49: 
50:         %>


An error occurred at line: [177] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [180] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [180] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
response cannot be resolved

An error occurred at line: [183] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [185] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [188] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [188] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [191] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [192] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:213)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:600)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:381)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:398)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:15:49.207 SEVERE [http-nio-8080-exec-34] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [Unable to compile class for JSP: 

An error occurred at line: [47] in the jsp file: [/excel.jsp]
Syntax error, insert "Finally" to complete TryStatement
44:                         }
45:                     }
46:                 }
47:             }
48: 
49: 
50:         %>


An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [184] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
response cannot be resolved

An error occurred at line: [185] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [187] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [193] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [194] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:] with root cause
	org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [47] in the jsp file: [/excel.jsp]
Syntax error, insert "Finally" to complete TryStatement
44:                         }
45:                     }
46:                 }
47:             }
48: 
49: 
50:         %>


An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [184] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
response cannot be resolved

An error occurred at line: [185] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [187] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [193] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [194] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:213)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:600)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:381)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:398)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:16:03.849 SEVERE [http-nio-8080-exec-25] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [Unable to compile class for JSP: 

An error occurred at line: [47] in the jsp file: [/excel.jsp]
Syntax error, insert "Finally" to complete TryStatement
44:                         }*/
45:                     }
46:                 }
47:             }
48: 
49: 
50:         %>


An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [184] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
response cannot be resolved

An error occurred at line: [185] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [187] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [193] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [194] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:] with root cause
	org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [47] in the jsp file: [/excel.jsp]
Syntax error, insert "Finally" to complete TryStatement
44:                         }*/
45:                     }
46:                 }
47:             }
48: 
49: 
50:         %>


An error occurred at line: [179] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "catch", Identifier expected

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [181] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved to a variable

An error occurred at line: [182] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [184] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
response cannot be resolved

An error occurred at line: [185] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [187] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
out cannot be resolved

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

An error occurred at line: [190] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved

An error occurred at line: [193] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
Syntax error on token "finally", { expected

An error occurred at line: [194] in the generated java file: [D:\Projetos\NetBeans\crud\tomcat\work\Catalina\localhost\PI\org\apache\jsp\excel_jsp.java]
_jspx_page_context cannot be resolved to a variable

Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:213)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:600)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:381)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:398)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:16:23.184 SEVERE [http-nio-8080-exec-33] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [24]

21:     <body>
22:         <%
23:                 Conexao conexao = new Conexao();
24:                 Connection con = conexao.abreConec();
25:                 PreparedStatement st;
26: 
27:                 String arquivo = "C:\\Users\\win\\Desktop\\dados.csv";


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:143)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
23-Nov-2023 17:17:46.770 SEVERE [http-nio-8080-exec-32] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PI] threw exception [An exception occurred processing [/excel.jsp] at line [24]

21:     <body>
22:         <%
23:                 Conexao conexao = new Conexao();
24:                 Connection con = conexao.abreConec();
25:                 PreparedStatement st;
26: 
27:                 String arquivo = "C:\\Users\\win\\Desktop\\dados.csv";


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Unknown database 'frequency'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at classes.Conexao.abreConec(Conexao.java:29)
		at org.apache.jsp.excel_jsp._jspService(excel_jsp.java:143)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
